kind: Service
apiVersion: v1
metadata:
 name: nginx
spec:
 type: NodePort
 selector:
  project: ashok
  component: backend
 ports:
  - protocal: tcp
    port: 80
    targetport: 80

---
kind: Pod
apiVersion: v1
metadata:
 name: backend
 labels:
  project: ashok
  component: backend
spec:
 containers:
 - name: nginx
   image: nginx      